language: php
dist: trusty
sudo: required
group: edge
 
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
 
before_script:
  - composer self-update
  - composer install --prefer-source
  - if [[ "$TRAVIS_PHP_VERSION" == '7.3' ]]; then composer require phpunit/phpunit 6.5.5; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.2' ]]; then composer require phpunit/phpunit 6.5.5; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require phpunit/phpunit 4.8.35; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require phpunit/phpunit 4.8.35; fi
 
script:
  - vendor/bin/phpunit
